application: frlrm-187801
version: 20171201t202404
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
- url: /scss
  static_dir: static/scss
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /vendor
  static_dir: static/vendor
- url: /video
  static_dir: static/video
- url: /.*
  script: views.main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest